spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testdb
    username: user
    password: password
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      register-mbeans: true
      pool-name: pool_db
  jpa:
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /sandbox

