version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:12'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=testdb
    volumes:
      - '/Users/jakimenko/Downloads/work/sandbox/data/postgres:/bitnami/postgresql'

# docker-compose -f testdb.yml up -d
# docker-compose -f testdb.yml down
